# Panda Fundmentals: Series, DataFrames, I/O and Inspection 

## What is Panda ? 

Pandas is a Python library for **data manipulation and analysis**, build on top of NumPy. 

Key points: 
- Provides 2 main data structures: `Series` (1D) and `DataFrame` (2D)
- Designed for working with **tabular data** (like Excel sheets, CSV files, SQL tables)

In real projects, the typical flow is: 

Raw data -> Pandas for cleaning & transformation -> NumPy/sklearn for modeling

## Series 

A **Series** is a one-dimensional labeled array. 

Think of it as: 
- A single column of a spreadsheet, with an **index** (row labels) and **values**
- Similar to a NumPy array, but with labels and more functionality.

For example,

In [5]:
import pandas as pd 

s1 = pd.Series([10,20,30,40])
s1

0    10
1    20
2    30
3    40
dtype: int64

### Series with custom index

In [6]:
s2 = pd.Series(
    data=[10,20,30],
    index=["a", "b", "c"],
    name="example_series"
)

print("Series values: ", s2.values)
print("Series index: ", s2.index)
print("Series dtype: ", s2.dtype)

Series values:  [10 20 30]
Series index:  Index(['a', 'b', 'c'], dtype='object')
Series dtype:  int64

### Series from dictionary

In [7]:
data_dict = {"apple": 3, "banana": 5, "orange": 2}
s3 = pd.Series(data_dict, name="fruit_count")
s3

apple     3
banana    5
orange    2
Name: fruit_count, dtype: int64

### Notes on Series 

- `index`: labels for the elements (can be strings, numbers, dates, etc..)
- `values`: the underlying NumPy array
- `dtype`: data type of the elements (int, float, object,...)

We can access elements by label or position: 
- `s2["a"]` -> by label 
- `s2[0]` -> by position

In [8]:
print("s2['a']  ->", s2["a"])
print("s2[0]    ->", s2[0])

print("\nSlice by position: ")
print(s1[1:3])

s2['a']  -> 10
s2[0]    -> 10

Slice by position:
1    20
2    30
dtype: int64

/tmp/ipykernel_228970/4230836977.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("s2[0]    ->", s2[0])

## DataFrames 

A **DataFrame** is a two-dimensional, tabular data structure with: 
- **Row** and **columns** (like an Excel sheet)
- Each column is a `Series`
- Row labels (index) and column labels (column names)

This is the main structure we will work with in Pandas

### Create DataFrame from dicts

In [14]:
# dictionary 
data = {
    "name": ["John", "Anna", "Peter", "Linda"],
    "age": [23, 25, 31, 29],
    "city": ["HCM", "Hanoi", "Danang", "HCM"]
}

# List of dictionaries 
records = [
    {"name": "John", "age": 23, "city": "HCM"},
    {"name": "Anna", "age": 25, "city": "Hanoi"},
    {"name": "Peter", "age": 31, "city": "Danang"},
]

df_people = pd.DataFrame(data)
df_people

    name  age    city
0   John   23     HCM
1   Anna   25   Hanoi
2  Peter   31  Danang
3  Linda   29     HCM

In [13]:
df_people_v2 = pd.DataFrame(records)
df_people_v2

    name  age    city
0   John   23     HCM
1   Anna   25   Hanoi
2  Peter   31  Danang

### Basic attributes of DataFrame

In [11]:
print("Shape (rows, columns): ", df_people.shape)
print("Columns: ", df_people.columns.tolist())
print("Index: ", df_people.index)
print("\nData types: ")
print(df_people.dtypes)

Shape (rows, columns):  (4, 3)
Columns:  ['name', 'age', 'city']
Index:  RangeIndex(start=0, stop=4, step=1)

Data types:
name    object
age      int64
city    object
dtype: object

### Reading Data from CSV

In [15]:
customers = pd.read_csv("data/customers-100.csv")

customers.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

#### Basic inspection

In [16]:
print("Shape: ", customers.shape)
print("\nColumns: ", customers.columns.tolist())

print("\nInfor:")
print(customers.info())

print("\nDescribe (numeric columns):")
print(customers.describe())

Shape:  (100, 12)

Columns:  ['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City', 'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date', 'Website']

Infor:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    object
 2   First Name         100 non-null    object
 3   Last Name          100 non-null    object
 4   Company            100 non-null    object
 5   City               100 non-null    object
 6   Country            100 non-null    object
 7   Phone 1            100 non-null    object
 8   Phone 2            100 non-null    object
 9   Email              100 non-null    object
 10  Subscription Date  100 non-null    object
 11  Website            100 non-null    object
dtypes: int64(1), object(11)
memory usage: 9.5+ KB
None

Describe (numeric columns):
            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

### Random sampling and tail 

- `.sample(n)` -> sample `n` random rows.
- `.tail()` -> last 5 rows (by default)

In [17]:
print("Random 3 rows:")
display(customers.sample(3))

print("\nLast 5 rows:")
display(customers.tail())

Random 3 rows:

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
19,20,0F60FF3DdCd7aB0,Joanna,Kirk,Mays-Mccormick,Jamesshire,French Polynesia,(266)131-7001x711,(283)312-5579x11543,tuckerangie@salazar.net,2021-09-24,https://www.camacho.net/
22,23,2FB0FAA1d429421,Colleen,Howard,Greer and Sons,Brittanyview,Paraguay,1935085151,(947)115-7711x5488,rsingleton@ryan-cherry.com,2020-08-19,http://paul.biz/
68,69,421a109cABDf5fa,Virginia,Dudley,Warren Ltd,Hartbury,French Southern Territories,027.846.3705x14184,+1-439-171-1846x4636,zvalencia@phelps.com,2021-01-31,http://hunter-esparza.com/

Last 5 rows:

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/